### ISSUE TITLE
集成sendcloud到rails app中

### ISSUE THREAD

**Issue by luckyyang** [luckyyang/sendcloud-demo#1]
可以用sendcloud提供的web api：

http://sendcloud.sohu.com/api-doc/web-api-ruby-examples

**Comment by luckyyang** [comment]
ruby的代码怎么集成到rails中比较合适呢？ @happypeter 定义一个module么？

**Comment by happypeter** [comment]
@luckyyang 一般和数据库没关系的代码放到 controller 里就行。对于 rails 来说， mailer 是有自己专门的处理方式，可以参考 rails 的 action mailer 文档或者参考 happycasts 的代码

**Comment by happypeter** [comment]
http://railscasts.com/episodes/206-action-mailer-in-rails-3

**Comment by luckyyang** [comment]
现在的代码已经实现了注册一个新用户之后给这个用户的邮箱发邮件了

**Comment by limingth** [comment]
我创建了一个新的 event，邀请了 luckyyang 和 happypeter ，不知道大家是否收到邮件了。 我这边还没有。

2014-07-08 16:41 GMT+08:00 Liujiyang notifications@github.com:

> 现在的代码已经实现了注册一个新用户之后给这个用户的邮箱发邮件了
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/luckyyang/sendcloud-demo/issues/1#issuecomment-48286069
> .

## 

Ming Li

**Comment by luckyyang** [comment]
目前还没有集成到毛豆里面，只是在这个repo里的我的开发环境下。

**Comment by limingth** [comment]
如果有新功能，等部署了再告诉大家吧，不然我都会去测试一下。

2014-07-08 17:15 GMT+08:00 Liujiyang notifications@github.com:

> 目前还没有集成到毛豆里面，只是在我的开发环境下。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/luckyyang/sendcloud-demo/issues/1#issuecomment-48289068
> .

## 

Ming Li

**Comment by luckyyang** [comment]
> 如果有新功能，等部署了再告诉大家吧，不然我都会去测试一下。

好的。集成到毛豆中的新功能一般会在ppweb那个repo中讨论。

**Comment by luckyyang** [comment]
如果要在线测试的话，我需要在我的aws上搭建一下rails的环境，aws上ubuntu是14.04的

**Comment by limingth** [comment]
aws 可以搭建 12.04 的环境，AMI 需要选择 不是默认的，有 12.04 的版本。（需要仔细找）

另外，我后来在 maodou.us 那台机器上，就部署的是 12.04 的版本。

登录方法：  ssh -i pplinux.pem ubuntu@maodou.us

2014-07-10 14:58 GMT+08:00 Liujiyang notifications@github.com:

> 如果要在线测试的话，我需要在我的aws上搭建一下rails的环境，aws上ubuntu是14.04的
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/luckyyang/sendcloud-demo/issues/1#issuecomment-48571352
> .

## 

Ming Li

**Comment by luckyyang** [comment]
我昨天环境都搭起来了，现在apache还有点小问题
![image](https://cloud.githubusercontent.com/assets/1963646/3547278/b647da6e-0893-11e4-87d8-2049742f9131.png)

**Comment by limingth** [comment]
https://github.com/contact

@luckyyang  可以为 maodou.io 做一个类似的页面吗？

我觉得风格上，咱们可以多抄一些 github 的，程序员看起来会很亲切。

2014-07-11 8:38 GMT+08:00 Liujiyang notifications@github.com:

> 我昨天环境都搭起来了，现在apache还有点小问题
> [image: image]
> https://cloud.githubusercontent.com/assets/1963646/3547278/b647da6e-0893-11e4-87d8-2049742f9131.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/luckyyang/sendcloud-demo/issues/1#issuecomment-48682359
> .

## 

Ming Li

**Comment by luckyyang** [comment]
这个可以做，但不是这个repo讨论的内容。这个repo只讨论sendcloud相关api的问题。

这属于ppweb的一个新功能，至于是否现在做以及是否要用email的方式实现，让 @happypeter 来决定吧

**Comment by happypeter** [comment]
提了 issue 了: https://github.com/happypeter/ppweb/issues/145

**Comment by luckyyang** [comment]
到http://dayangyou.com/ 新注册一个用户，指定的email就可以收到一封邮件了

**Comment by limingth** [comment]
成功收到 欢迎来到毛豆网 的邮件。

用这个方式来进行注册，比之前填写用户密码的方式要简单多了。

在 2014年7月12日 下午12:30，Liujiyang notifications@github.com写道：

> 到http://dayangyou.com/ 新注册一个用户，指定的email就可以收到一封邮件了
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/luckyyang/sendcloud-demo/issues/1#issuecomment-48802105
> .

## 

Ming Li

**Comment by luckyyang** [comment]
正常的注册还是需要密码的，我这只是测试email的功能
