### ISSUE TITLE
怎么去申请邮件模版

### ISSUE THREAD

**Issue by guoyoujin** [luckyyang/sendcloud-demo#10]
我想实现一个表格的模版，表格内容是变换的，怎么申请？

**Comment by guoyoujin** [comment]
发送的时候出现如下错误：

end of file reached
    from /Users/guoyoujin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/openssl/buffering.rb:182:in `sysread_nonblock'
    from /Users/guoyoujin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/openssl/buffering.rb:182:in`read_nonblock'
    from /Users/guoyoujin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/protocol.rb:153:in `rbuf_fill'
    from /Users/guoyoujin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/protocol.rb:134:in`readuntil'
    from /Users/guoyoujin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/protocol.rb:144:in `readline'
    from /Users/guoyoujin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/smtp.rb:938:in`recv_response'
    from /Users/guoyoujin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/smtp.rb:924:in `block in getok'
    from /Users/guoyoujin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/smtp.rb:948:in`critical'
    from /Users/guoyoujin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/smtp.rb:922:in `getok'
    from /Users/guoyoujin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/smtp.rb:916:in`quit'
    from /Users/guoyoujin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/smtp.rb:616:in `do_finish'
    from /Users/guoyoujin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/smtp.rb:523:in`ensure in start'
    from /Users/guoyoujin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/smtp.rb:523:in `start'
    from /Users/guoyoujin/.rvm/gems/ruby-2.1.3/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in`deliver!'
    from /Users/guoyoujin/.rvm/gems/ruby-2.1.3/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
    from /Users/guoyoujin/.rvm/gems/ruby-2.1.3/gems/mail-2.6.3/lib/mail/message.rb:238:in`deliver'
    from /Users/guoyoujin/.rvm/gems/ruby-2.1.3/gems/mail-2.6.3/lib/mail/mail.rb:140:in `deliver'

**Comment by luckyyang** [comment]
你找 sendcloud 客服，让他们去掉你的模板验证，要不然每次发邮件都检查你的邮件和模板的匹配度，经常导致错误无法发送

**Comment by guoyoujin** [comment]
问了客服，他们说放开权限得付费使用2周，还得通过审核才行，感觉太复杂了

**Comment by guoyoujin** [comment]
@luckyyang 他们说需要达到要求：
请您参考模板免审条件：
付费认证为企业用户
付费使用了两周以上，账户信誉度在80分以上。
邮件需求以触发类型为主。
无违规发送记录。
账户余额在500元以上
满足以上几条才可以申请的；
这个信誉度就是个问题啊

**Comment by luckyyang** [comment]
我当时遇到问题，也不满足这个条件，他们主动说给我开放权限的，我觉得可以商量，你厚脸皮打他们客服电话争取一下。
