### ISSUE TITLE
邮件样本设置

### ISSUE THREAD

**Issue by luckyyang** [luckyyang/sendcloud-demo#2]
http://sendcloud.sohu.com/api-doc/web-api-ruby-examples
http://sendcloud.sohu.com/sendcloud/api-doc/web-api-html-examples

邮件的subject/标题和html/正文都要匹配sendcloud中设置的邮件样本，匹配度不对的话，发送邮件会失败的，登录sendcloud网站后在 **设置-》邮件样本** 中可以进行设置和匹配度测试

匹配不对的话，会报553错误 =》 553    'template_validate not match"

**Comment by luckyyang** [comment]
使用和邮件样本一样的邮件内容进行测试：
- ruby 脚本测试：发送成功（200 success）
- html页面测试：发送成功（200 success）

@happypeter @billie66 @limingth 看一下收到了没有？

**Comment by billie66** [comment]
收到

**Comment by billie66** [comment]
我又收到一封

**Comment by luckyyang** [comment]
没错，我又发了一封

**Comment by luckyyang** [comment]
现在触发邮件也成功了，你们也应该收到了一封确认注册成功的邮件：
![image](https://cloud.githubusercontent.com/assets/1963646/3492945/91962164-05b2-11e4-9374-60d0af6acea0.png)

**Comment by luckyyang** [comment]
邮件样本和子账号是有关系的 https://github.com/luckyyang/sendcloud-demo/issues/3

**Comment by happypeter** [comment]
我这边也收到邮件了
