### ISSUE TITLE
子账号和邮件样本

### ISSUE THREAD

**Issue by luckyyang** [luckyyang/sendcloud-demo#3]
http://mednoter.com/SendCloud.html
子帐号

每个域名下可以设置多个子帐号。建议一个业务启用一个子帐号，分析数据时便于细分。

从而非常方便的统计每个业务每天的发送量、无效邮件、退信、被 ESPs 判断为垃圾邮件、垃圾邮件举报、打开率等等。

比如我就是这么干的。

transactional email
postmaster@boohee-register.sendcloud.org（注册激活）
postmaster@boohee-notification.sendcloud.org（提醒）
postmaster@boohee-recommand.sendcloud.org（个性化推荐）
postmaster@boohee-recall.sendcloud.org（唤醒老用户）

bulk email
postmaster@boohee-weeklydigest.sendcloud.org（每周精选）

**Comment by luckyyang** [comment]
子账号和邮件样本都分为`触发邮件`和`批量邮件`类型，目前批量邮件可以发送成功，拿批量邮件发送来说明代码大概流程应该是这样的：
- 选择批量邮件对应的子账号
- 邮件标题和内容填写时注意要匹配批量邮件的某一个邮件样本
- 发送成功

**Comment by happypeter** [comment]
邮件营销是一个很重要的专业领域，所以肯定 sendcloud 提供给客户的功能也会很丰富。不过项目初期还是要尽量保持代码的简单，便于维护。“刚刚够用”是王道。

**Comment by luckyyang** [comment]
对，这里主要是阐述一下流程

**Comment by luckyyang** [comment]
> 您上传的邮件样本：welcome to maodou，审核通过，后续可发送此样本对应的邮件。
> 温馨提醒您：后续发送中邮件内容必须与已上传的邮件样本大部分一致（包括image个数、链接个数与附件个数），仅存在必要的变量替换或修改。
> 若所发的邮件内容无法与样本匹配，API会话阶段将返回错误代码：”553:template_validate not match”。

**Comment by happypeter** [comment]
@luckyyang 靠，还有这个要求，真是挺高级的。

**Comment by luckyyang** [comment]
sendcloud的文档还是没有那么友好啊，本来挺简单的一个事，感觉有点绕
