### ISSUE TITLE
邮件的 html 模板

### ISSUE THREAD

**Issue by happypeter** [luckyyang/sendcloud-demo#4]
这个 @billie66 是有经验的，参考 https://github.com/happypeter/happycasts/blob/master/app/views/happy_mailer/new_ep_release.html.erb

@luckyyang 动手的时候如果遇到问题可以问 @billie66

**Comment by luckyyang** [comment]
好的

**Comment by happypeter** [comment]
@luckyyang 如果觉得麻烦也可以不弄，毕竟这个 repo 主要还是要玩转 sendcloud 的 API

**Comment by luckyyang** [comment]
恩 这个不着急弄
