### ISSUE TITLE
邮箱设置的问题

### ISSUE THREAD

**Issue by luckyyang** [luckyyang/sendcloud-demo#5]
这种带有密码的配置要放在哪里比较合适呢？ @happypeter happycasts是怎么做的？代码里我没找到相关的设置

/config/initializers/setup_mail.rb

```
ActionMailer::Base.smtp_settings = {
  :address              => "smtp.gmail.com",
  :port                 => 587,
  :domain               => "asciicasts.com",
  :user_name            => "asciicasts",
  :password             => "secret",
  :authentication       => "plain",
  :enable_starttls_auto => true
}
```

**Comment by limingth** [comment]
通过环境变量？可以加到每次开机执行的脚本中 export

2014-07-08 16:44 GMT+08:00 Liujiyang notifications@github.com:

> 这种带有密码的配置要放在哪里比较合适呢？ @happypeter https://github.com/happypeter
> happycasts是怎么做的？代码里我没找到相关的设置
> 
> /config/initializers/setup_mail.rb
> 
> ActionMailer::Base.smtp_settings = {
>   :address              => "smtp.gmail.com",
>   :port                 => 587,
>   :domain               => "asciicasts.com",
>   :user_name            => "asciicasts",
>   :password             => "secret",
>   :authentication       => "plain",
>   :enable_starttls_auto => true
> }
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/luckyyang/sendcloud-demo/issues/5.

## 

Ming Li

**Comment by luckyyang** [comment]
这个应该是放到rails app中就可以

**Comment by happypeter** [comment]
> 通过环境变量？

这是比较常见的做法，也是 heroku 上唯一可行的办法

不过我自己觉得更为方便一点的做法是采用 settingslogic，基本步骤：
- 将 config/settings.yml 写入 .gitignore
- 所有的机密信息就都写到 settings.yml，每次部署服务器的时候，手动上传这个文件
- 要写的代码也就这么几行：https://github.com/happypeter/happycasts/blob/master/app/models/settings.rb

**Comment by billie66** [comment]
settingslogic 这个 gem 已经使用了，直接把密码写到 settings.yml 文件中就可以了

**Comment by happypeter** [comment]
@billie66 这里讨论的不是 ppweb 项目代码，是 @luckyyang 自己的小 demo

**Comment by billie66** [comment]
哦，知道了

**Comment by luckyyang** [comment]
done
