### ISSUE TITLE
用户确认注册

### ISSUE THREAD

**Issue by luckyyang** [luckyyang/sendcloud-demo#6]
用户在网站上注册后，会受到一封邮件。邮件中最好是有一个确认注册的链接，用户点击后才注册成功。

**Comment by happypeter** [comment]
这个应该是确认邮箱主人用的，实际中是个挺重要的安全策略，但是咱们这里做的是 sendcloud 的 demo 这一步我觉得可以不做，因为这个功能跟 sendcloud 本身的使用逻辑好像没有太直接的关系。

**Comment by luckyyang** [comment]
对，和sendcloud关系不大。先不管它了
